<?php
// $Id: xoops_version.php,v 1.1 2004/01/29 14:45:23 buennagel Exp $
//  ------------------------------------------------------------------------ //
//                XOOPS - PHP Content Management System                      //
//                    Copyright (c) 2000 XOOPS.org                           //
//                       <http://www.xoops.org/>                             //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //

$modversion['name'] = _MI_SURVEY_NAME;
$modversion['version'] = 0.11;
$modversion['description'] = _MI_SURVEY_DESC;
$modversion['author'] = "Yoshi.S<br />( http://www.bluemooninc.biz/ )";
$modversion['credits'] = "<a href=\"http://www.bluemooninc.biz/\" target=\"_blank\">Bluemoon inc.</a>"
."<br>Based By <a href=\"http://sourceforge.net/projects/phpesp\" target=\"_blank\">phpESP project</a>";
$modversion['help'] = "bmef.html";
$modversion['license'] = "GPL see LICENSE";
$modversion['official'] = 0;
$modversion['image'] = "images/bmef_slogo.png";
$modversion['dirname'] = "bmef";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = "bmef_realm";
$modversion['tables'][1] = "bmef_respondent";
$modversion['tables'][2] = "bmef_designer";
$modversion['tables'][3] = "bmef_survey" ;
$modversion['tables'][4] = "bmef_question_type" ;
$modversion['tables'][5] = "bmef_question" ;
$modversion['tables'][6] = "bmef_question_choice" ;
$modversion['tables'][7] = "bmef_access" ;
$modversion['tables'][8] = "bmef_response" ;
$modversion['tables'][9] = "bmef_response_bool" ;
$modversion['tables'][10] = "bmef_response_single" ;
$modversion['tables'][11] = "bmef_response_multiple" ;
$modversion['tables'][12] = "bmef_response_rank" ;
$modversion['tables'][13] = "bmef_response_text" ;
$modversion['tables'][14] = "bmef_response_other" ;
$modversion['tables'][15] = "bmef_response_date" ;


// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/manage.php";
$modversion['adminmenu'] = "admin/menu.php";

$modversion['templates'][1]['file'] = 'bmef_index.html';
$modversion['templates'][1]['description'] = '';
$modversion['templates'][2]['file'] = 'bmef_view.html';
$modversion['templates'][2]['description'] = '';
$modversion['templates'][3]['file'] = 'bmef_results.html';
$modversion['templates'][3]['description'] = '';
// Menu
$modversion['hasMain'] = 1;
$modversion['sub'][1]['name'] = _MI_SURVEY_ADMIN;
$modversion['sub'][1]['url'] = "admin/manage.php";

// Blocks
$modversion['blocks'][1]['file'] = "bmef_top.php";
$modversion['blocks'][1]['name'] = _MI_SURVEY_BNAME1;
$modversion['blocks'][1]['description'] = "Bluemoon Multi Entry Form";
$modversion['blocks'][1]['show_func'] = "b_bmef_show";
$modversion['blocks'][1]['edit_func'] = "b_bmef_edit";
$modversion['blocks'][1]['options'] = "1";
$modversion['blocks'][1]['template'] = 'bmef_block.html';

$modversion['templates'][] = array(
	'file'        => 'bmef_list.html',
	'description' => 'Survey List'
);
$modversion['templates'][] = array(
	'file'        => 'bmef_survey.html',
	'description' => 'Survey Render'
);

// Menu
$modversion['hasMain'] = 1;

// Comments
$modversion['hasComments'] = 1;
$modversion['comments']['pageName'] = 'pollresults.php';
$modversion['comments']['itemName'] = 'poll_id';
?>